export const STORY_FETCH_ACTION = 'STORY_FETCH_ACTION';
export const STORY_ERROR_ACTION = 'STORY_ERROR_ACTION';
export const STORY_LIST_ACTION = 'STORY_LIST_ACTION';
export const STORY_ITEM_ACTION = 'STORY_ITEM_ACTION';
